INSERT INTO CUSTOM_USER(ID,USERNAME,PASSWORD,ROLE,TASK_ID) VALUES (1,'admin', 'admin', 'ROLE_ADMIN',1);
INSERT INTO CUSTOM_USER(ID,USERNAME,PASSWORD,ROLE,TASK_ID) VALUES (2,'user', 'user', 'ROLE_USER',2);
INSERT INTO role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO role (id, name) VALUES (2, 'ROLE_ADMIN');